version: '3'

services:
  web_nginx:
    image: nginx:1.17.9-alpine
    depends_on:
    - app_django
    ports:
      - "${PORT}:443"
    volumes:
      - ./web_nginx/conf.d:/etc/nginx/conf.d
      - ./web_nginx/ssl:/etc/nginx/ssl
      - staticdata:/app/static/
    networks:
      - nginx_network

  app_django:
    image: app_django_test_${src_tag}
    volumes:
      - staticdata:/app/static/
    expose: 
      - 8000
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge

volumes:
  staticdata:
